# Generated by Django 6.1.1 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('TRIAL_ACTIVE', 'Trial Active'), ('EXPIRED', 'Expired'), ('ACTIVE', 'Active')], default='TRIAL_ACTIVE', max_length=20)),
                ('trial_started_at', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
