# Generated by Django 6.1.1 on 2026-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('TRIAL_ACTIVE', 'Trial Active'), ('EXPIRED', 'Expired'), ('ACTIVE', 'Active'), ('PENDING', 'Pending')], default='TRIAL_ACTIVE', max_length=20),
        ),
    ]
