# Generated by Django 6.1.1 on 2026-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('TRIAL_ACTIVE', 'Trial Active'), ('EXPIRED', 'Expired'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='TRIAL_ACTIVE', max_length=20),
        ),
    ]
