# Generated by Django 6.1.1 on 2026-09-25 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_tenant'),
        ('learning', '0003_rename_assignment_at_courseassignment_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_assignment'),
        ),
    ]
